language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
services:
  - docker
before_install:
  - docker pull redislabs/redisgears
install:
  - pip install -r src/requirements-test.txt
  - pip install .
script:
  - isort ./**/*.py --check-only
  - flake8 ./src/
  - black ./src/ --check
  - mypy ./src/
  - pytest --cov=redgrease --cov-report=xml
after_success:
  - codecov

