language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
services:
  - docker
before_install:
  - docker pull redislabs/redisgears
install:
  - pip install -r src/requirements-test.txt
script:
  - python -m isort ./**/*.py --check-only
  - python -m flake8 ./src/
  - python -m black ./src/ --check
  - python -m mypy ./src/
  - python -m pytest --cov=redgrease --cov-report=xml
after_success:
  - codecov

