version: '3.7'

services:
  redisgears:
    image: redislabs/redisgears:latest
    ports:
    - 127.0.0.1:${REDGREASE_PORT:-6379}:6379
    
  redgrease:
    image: lyngon/redgrease
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
    - $PWD/examples:/redgrease/watch/examples
    command: -w -r /redgrease/watch/examples 
    environment:
    - SERVER=redisgears
    - PORT=${REDGREASE_PORT:-6379}
    depends_on:
    - redisgears
