version: '3.7'

services:
  redisgears:
    image: redislabs/redisgears:latest
    ports:
    - 6379:6379
    
  redgrease:
    image: lyngon/redgrease
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
    - $PWD/examples:/redgrease/watch/examples
    command: -w 1.2 -r /redgrease/watch/examples 
    environment:
    - SERVER=redisgears
    depends_on:
    - redisgears
