version: '3.7'

services:
  redisgears:
    image: redislabs/redisgears:latest
    ports:
    - 6379:6379
    
  redgrease:
    image: lyngon/redgrease
    name: redgrease
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
    - $PWD/examples:/redgrease/watch/examples
    environment:
    - TARGET=resdisgears
    - REGIYSTRATIONS_KEY=/redgrease/regs
    depends_on:
    - redisgears
