# This workflow will install Python development dependencies and run tests

name: tests

on:
  pull_request:
    branches:
    - main


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        redisgears-container:
        - redislabs/redisgears:1.0.5
        - redislabs/redisgears:1.0.6
        - redislabs/redisgears:1.2.0
        - redislabs/redisgears:1.2.1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r src/requirements-dev.txt
        python -m pip install .[all]
      
    - name: Test with pytest
      env:
        REDGREASE_RUNTIME_PACKAGE: redgrease[runtime]@git+https://github.com/lyngon/redgrease.git@${{ github.head_ref }}
        REDISGEARS_IMAGE: ${{ matrix.redisgears-container }}
      run: pytest --cov=redgrease --cov-report=xml
      
    - name: Submit code coverage reports
      uses: codecov/codecov-action@v1
      with:
        verbose: true

    - name: Readme hacks
      run: echo "Readme hacks go here!"
